### ISSUE TITLE
Cant find radare2rc configuaration file 

### ISSUE THREAD

**Issue by saneeha-amir** [radareorg/radare2-r2pipe#144]
Dear all,

I am trying to work on the analysis of android memory dump. In order to open the dump from r2pipe i need to set the configuration variable of "bin.cache" to true. For this purpose I need to access the configuration file which contains all the configuration variables. 
The problem is that I am unable to find the file at following locations:

/usr/share/radare2/radare2rc
~/.radare2rc
~/.config/radare2/radare2rc
~/.config/radare2/radare2rc.d/

This problem of missing configuration file is discussed in the issue " Can't find radare2rc #7761 ". It is been stated that if you are unable to find the radare2rc file you may create it yourself.

Please guide what should be the content of this file if I create it my self and if it is correct way of changing a certain configuration variable. 

Note: I have also tried to run the installer again. It updates radare2 but still the file is not present. 

Any help is appreciated.
Thanks

**Comment by trufae** [comment]
This file doesn't exist until the user creates it, all the paths where r2 checks for it are listed in `r2 -hh` so you know the paths already. that's a common behaviour in unix applications, so i dont think r2 should create that file.

There's no r2 installer :? but iasume you run sys/install.sh again maybe? that wont create that script either, because thats a system installation and the script should be created by every user in the system that wants custom vars.

**Comment by trufae** [comment]
Also, this is a ticket that should be filled inthe r2 repo, not in r2pipe

**Comment by saneeha-amir** [comment]
Alright i understood. Thanks alot for explaining.

The configuration can be made by defining the flag as under:
r= r2pipe.open('./dump',flags=['-ebin.cache=true'])

There is no need to find and edit the configuration file.
